import type { Language } from "@/contexts/language-context"

const translations: Record<Language, Record<string, string>> = {
  en: {
    "Clear sky": "Clear sky",
    "Mainly clear": "Mainly clear",
    "Partly cloudy": "Partly cloudy",
    Overcast: "Overcast",
    Fog: "Fog",
    "Depositing rime fog": "Depositing rime fog",
    "Light drizzle": "Light drizzle",
    "Moderate drizzle": "Moderate drizzle",
    "Dense drizzle": "Dense drizzle",
    "Slight rain": "Slight rain",
    "Moderate rain": "Moderate rain",
    "Heavy rain": "Heavy rain",
    "Slight rain showers": "Slight rain showers",
    "Moderate rain showers": "Moderate rain showers",
    "Violent rain showers": "Violent rain showers",
    Thunderstorm: "Thunderstorm",
    "Thunderstorm with slight hail": "Thunderstorm with slight hail",
    "Thunderstorm with heavy hail": "Thunderstorm with heavy hail",
    "Unknown conditions": "Unknown conditions",
    "Heavy rainfall with thunderstorm risk": "Heavy rainfall with thunderstorm risk",
    "Moderate rainfall expected": "Moderate rainfall expected",
    "Light precipitation conditions": "Light precipitation conditions",
    "High flood risk in low-lying areas": "High flood risk in low-lying areas",
    "Moderate flood risk": "Moderate flood risk",
    "Low flood risk": "Low flood risk",
    "Strong sustained winds expected": "Strong sustained winds expected",
    "Moderate wind conditions": "Moderate wind conditions",
    "Calm wind conditions": "Calm wind conditions",
    "High risk due to soil saturation": "High risk due to soil saturation",
    "Moderate risk in steep areas": "Moderate risk in steep areas",
    "Low landslide risk": "Low landslide risk",
    "Moderate conditions": "Moderate conditions",
    "Stable conditions": "Stable conditions",
    "Low seismic activity": "Low seismic activity",
    "Minor seismic activity": "Minor seismic activity",
    "Light seismic activity detected": "Light seismic activity detected",
    "Moderate seismic activity": "Moderate seismic activity",
    "Strong seismic activity detected": "Strong seismic activity detected",
  },
  tl: {
    "Clear sky": "Malinaw na kalangitan",
    "Mainly clear": "Karamihan ay malinaw",
    "Partly cloudy": "Bahagyang maulap",
    Overcast: "Maulap",
    Fog: "Ulap",
    "Depositing rime fog": "Depositing rime fog",
    "Light drizzle": "Magaan na ulan",
    "Moderate drizzle": "Katamtamang ulan",
    "Dense drizzle": "Malalim na ulan",
    "Slight rain": "Kaunting ulan",
    "Moderate rain": "Katamtamang ulan",
    "Heavy rain": "Mabigat na ulan",
    "Slight rain showers": "Kaunting ulan",
    "Moderate rain showers": "Katamtamang ulan",
    "Violent rain showers": "Malakas na ulan",
    Thunderstorm: "Kidlat at Kulog",
    "Thunderstorm with slight hail": "Kidlat at Kulog na may kaunting yelo",
    "Thunderstorm with heavy hail": "Kidlat at Kulog na may mabigat na yelo",
    "Unknown conditions": "Hindi kilalang kondisyon",
    "Heavy rainfall with thunderstorm risk": "Mabigat na ulan na may panganib ng kidlat",
    "Moderate rainfall expected": "Inaasahang katamtamang ulan",
    "Light precipitation conditions": "Magaan na kondisyon ng ulan",
    "High flood risk in low-lying areas": "Mataas na panganib ng baha sa mababang lugar",
    "Moderate flood risk": "Katamtamang panganib ng baha",
    "Low flood risk": "Mababang panganib ng baha",
    "Strong sustained winds expected": "Malakas na patuloy na hangin",
    "Moderate wind conditions": "Katamtamang kondisyon ng hangin",
    "Calm wind conditions": "Maayos na kondisyon ng hangin",
    "High risk due to soil saturation": "Mataas na panganib dahil sa basang lupa",
    "Moderate risk in steep areas": "Katamtamang panganib sa mataas na lugar",
    "Low landslide risk": "Mababang panganib ng landslide",
    "Moderate conditions": "Katamtamang kondisyon",
    "Stable conditions": "Matatag na kondisyon",
    "Low seismic activity": "Mababang seismic activity",
    "Minor seismic activity": "Maliit na seismic activity",
    "Light seismic activity detected": "Magaan na seismic activity na natuklasan",
    "Moderate seismic activity": "Katamtamang seismic activity",
    "Strong seismic activity detected": "Malakas na seismic activity na natuklasan",
  },
}

export function translateWeatherDescription(description: string, language: Language = "en"): string {
  return translations[language][description] || translations["en"][description] || description
}
